---
name: "Jellyfin Xtream"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.7.2.0-ashik-alpha0"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Stream content from an Xtream-compatible server."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
category: "Live TV"
owner: "ashikslab"
artifacts:
  - "Jellyfin.Xtream.dll"
changelog: >
  Revert to pure upstream logic - testing with jellypig tvOS client fix
